server:
  port: 8089
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.129.212.155:3306/mycard?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
  redis:
    database: 0
    host: 8.129.212.155
#    host: localhost
    port: 6379
    password:
    timeout: 500
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: -1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chen.mycardsystembackstage.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
logging:
  config: classpath:log.xml